# Tomcat settings
server:
  port: ${SERVER_PORT:8900}

# Management settings
management:
  endpoints:
    web:
      exposure:
        include: "*"

# Logging settings
logging:
  level:
    root: ERROR
    org:
      springframework:
        security: INFO
        web: ERROR
      hibernate: INFO
      kon: DEBUG
  file:
    path: ${LOGGING_FILE_PATH:./}
    name: ./log/oss.log
  logback:
    rollingpolicy:
      max-file-size: ${LOGGING_FILE_MAX_SIZE:100MB}
      max-history: ${LOGGING_FILE_MAX_HISTORY:50}

# Spring settings
spring:
  profiles:
    active: dev
  application:
    name: oss-achieve

# Oss settings
oss:
  endpoint: ${OSS_ENDPOINT:https://oss-cn-hangzhou.aliyuncs.com}
  accessKeyId: ${OSS_ACCESS_KEY_ID:WJ0125KNWTSW}
  accessKeySecret: ${OSS_ACCESS_KEY_SECRET:92eb026ba2c3215f36e902}

